[package]
name = "mocks"
version = "0.1.0"
authors = ["Oli Dacombe <olidacombe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wiremock = "0.5.2"
